/*
 * SPDX-FileCopyrightText: 2025 OmniAPK
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package com.aurora.store.util

/**
 * Helper class to generate direct APKMirror URLs for popular apps.
 * APKMirror URL format: https://www.apkmirror.com/apk/{publisher}/{app-slug}/
 * 
 * For apps not in the mapping, falls back to search URL.
 */
object APKMirrorUrlHelper {

    /**
     * Mapping of package names to their APKMirror paths.
     * Format: packageName -> "publisher/app-slug"
     * 
     * This comprehensive list was generated using Gemini AI via the
     * generate_apkmirror_mapping.py script in the /scripts folder.
     */
    private val packageMappings = mapOf(
        // =====================================================================
        // SOCIAL MEDIA & MESSAGING
        // =====================================================================
        "com.whatsapp" to "whatsapp-inc/whatsapp",
        "com.whatsapp.w4b" to "whatsapp-inc/whatsapp-business",
        "com.instagram.android" to "facebook-2/instagram",
        "com.instagram.lite" to "facebook-2/instagram-lite",
        "com.facebook.katana" to "facebook-2/facebook",
        "com.facebook.orca" to "facebook-2/messenger",
        "com.facebook.lite" to "facebook-2/facebook-lite",
        "com.facebook.mlite" to "facebook-2/messenger-lite",
        "com.facebook.pages.app" to "facebook-2/facebook-pages",
        "com.threads.android" to "facebook-2/threads",
        "com.twitter.android" to "twitter-inc/x",
        "com.zhiliaoapp.musically" to "tiktok/tiktok",
        "com.zhiliaoapp.musically.go" to "tiktok-pte-ltd/tiktok-lite",
        "com.ss.android.ugc.aweme" to "tiktok/tiktok",
        "org.telegram.messenger" to "telegram-messenger/telegram",
        "com.snapchat.android" to "snapchat-inc/snapchat",
        "com.discord" to "discord-inc/discord",
        "com.reddit.frontpage" to "reddit-inc/reddit",
        "com.pinterest" to "pinterest/pinterest",
        "com.linkedin.android" to "linkedin/linkedin",
        "tv.twitch.android.app" to "twitch-interactive/twitch",
        "com.tencent.mm" to "tencent/wechat",
        "com.viber.voip" to "viber-media-s-a-r-l/viber",
        "jp.naver.line.android" to "line-corporation/line",
        "com.skype.raider" to "microsoft-corporation/skype",
        "com.vkontakte.android" to "vkontakte/vk",
        "com.tumblr" to "tumblr/tumblr",
        "com.bereal.ft" to "bereal/bereal",
        "com.quora.android" to "quora/quora",
        "com.imo.android.imoim" to "imo/imo",
        "com.kakao.talk" to "kakao-corp/kakaotalk",
        
        // Dating Apps
        "com.tinder" to "tinder/tinder",
        "com.bumble.app" to "bumble-holding-limited/bumble",
        "com.badoo.mobile" to "badoo/badoo",
        "com.hinge.android" to "hinge/hinge",
        "com.okcupid.okcupid" to "okcupid/okcupid",
        "com.match.android.matchmobile" to "match-group-llc/match",
        "com.happn.app" to "happn/happn",
        "com.grindrapp.android" to "grindr-llc/grindr",

        // =====================================================================
        // MUSIC & AUDIO
        // =====================================================================
        "com.spotify.music" to "spotify-ab/spotify",
        "com.spotify.lite" to "spotify-ab/spotify-lite",
        "com.google.android.apps.youtube.music" to "google-inc/youtube-music",
        "com.apple.android.music" to "apple-inc/apple-music",
        "com.amazon.mp3" to "amazon-mobile-llc/amazon-music",
        "com.soundcloud.android" to "soundcloud/soundcloud",
        "com.deezer.android.app" to "deezer-mobile/deezer",
        "com.pandora.android" to "pandora-media-inc/pandora",
        "com.shazam.android" to "shazam/shazam",
        "com.audible.application" to "amazon-mobile-llc/audible",
        "fm.castbox.audiobook.radio.podcast" to "castbox/castbox",
        "com.anghami" to "anghami/anghami",
        "com.audiomack" to "audiomack/audiomack",
        "com.pocketcasts.android" to "shiftyjelly/pocket-casts",
        "com.gaana" to "gaana-com/gaana",
        "com.jio.media.jiobeats" to "jiosaavn/jiosaavn",
        "com.clearchannel.iheartradio.controller" to "iheartmedia-inc/iheartradio",
        "tunein.player" to "tunein-inc/tunein-radio",
        "com.aspiro.tidal" to "aspiro-tidal/tidal",
        "com.mixcloud.player" to "mixcloud/mixcloud",
        "com.bandcamp.android" to "bandcamp/bandcamp",
        "com.smule.singandroid" to "smule/smule",
        "com.starmakerinteractive.starmaker" to "starmakerinteractive/starmaker",
        "com.boomplay.music" to "boomplay-inc/boomplay",
        "ru.yandex.music" to "yandex-inc/yandex-music",
        "com.qobuz.music" to "qobuz/qobuz",
        "com.musixmatch.android.lyrify" to "musixmatch/musixmatch-lyrics-music",
        "com.sonos.acr2" to "sonos-inc/sonos",
        "com.soundhound.android.core" to "soundhound-inc/soundhound",
        "com.djit.apps.edjing.pro" to "djit/edjing-mix",
        "com.noisli.noisli" to "noisli/noisli",
        "com.rubycell.podcast.republic" to "rubycell/podcast-republic",
        "com.stitcher.app" to "stitcher/stitcher",
        "com.podcast.podcasts" to "google-inc/google-podcasts",
        "com.spreaker.android.studio" to "spreaker/spreaker",

        // =====================================================================
        // SHOPPING & E-COMMERCE
        // =====================================================================
        "com.amazon.mShop.android.shopping" to "amazon-com/amazon-shopping",
        "com.ebay.mobile" to "ebay-inc/ebay",
        "com.alibaba.aliexpresshd" to "alibaba-group/aliexpress",
        "com.shopee.id" to "shopee/shopee",
        "com.lazada.android" to "lazada/lazada",
        "com.wish.android" to "contextlogic/wish",
        "com.shein.android" to "shein-group-ltd/shein",
        "com.walmart.android" to "walmart/walmart",
        "com.target.ui" to "target-corporation/target",
        "com.etsy.android" to "etsy/etsy",
        "com.costco.app.android" to "costco/costco",
        "com.bestbuy.android" to "best-buy/best-buy",
        "com.nike.omega" to "nike/nike",
        "com.adidas.app" to "adidas/adidas",
        "com.hm.goe" to "h-m/h-m",
        "com.zara.zara" to "inditex/zara",
        "com.sephora" to "sephora/sephora",
        "com.ulta.ulta" to "ulta-beauty/ulta-beauty",
        "com.ikea.kompan" to "ikea/ikea",
        "com.homedepot" to "home-depot/home-depot",
        "com.lowes.android" to "lowes/lowe-s",
        "com.wayfair.wayfair" to "wayfair/wayfair",
        "com.macys.android" to "macys/macys",
        "com.nordstrom.app" to "nordstrom-inc/nordstrom",
        "com.kohls.mcommerce.opal" to "kohls/kohls",
        "com.jcpenney.android" to "jcpenney/jcpenney",
        "com.samsclub.mobile" to "walmart/sams-club",
        "com.walgreens.android" to "walgreens/walgreens",
        "com.cvs.launchers.cvs" to "cvs/cvs",
        "com.kroger.mobile" to "kroger/kroger",
        "com.mercari" to "mercari-inc/mercari",
        "com.poshmark.app" to "poshmark/poshmark",
        "com.offerup" to "offerup/offerup",
        "com.letgo.an" to "letgo/letgo",
        "com.dhgate.buyerapp" to "dhgate/dhgate",
        "com.banggood.client" to "banggood/banggood",
        "com.gearbest.en" to "gearbest/gearbest",

        // =====================================================================
        // FINANCE & BANKING
        // =====================================================================
        "com.paypal.android.p2pmobile" to "paypal/paypal",
        "com.venmo" to "venmo/venmo",
        "com.squareup.cash" to "square-inc/cash-app",
        "com.google.android.apps.walletnfcrel" to "google-inc/google-wallet",
        "com.binance.dev" to "binance/binance",
        "com.coinbase.android" to "coinbase/coinbase",
        "com.robinhood.android" to "robinhood/robinhood",
        "com.revolut.revolut" to "revolut-ltd/revolut",
        "com.wise.android" to "wise/wise",
        "com.crypto.exchange" to "crypto-com/crypto-com",
        "com.trustwallet.app" to "trustwallet/trust-wallet",
        "io.metamask" to "consensys/metamask",
        "com.bybit.app" to "bybit/bybit",
        "com.okex.android" to "okx/okx",
        "com.kucoin.market" to "kucoin/kucoin",
        "com.kraken.trade" to "kraken/kraken",
        "piuk.blockchain.android" to "blockchain-com/blockchain-com",
        "com.bitfinex.mobileapp" to "bitfinex/bitfinex",
        "exodusmovement.exodus" to "exodusmovement/exodus",
        "com.ledger.live" to "ledger/ledger-live",
        "com.plaid.link" to "plaid/plaid",
        "com.mint" to "intuit-inc/mint",
        "com.intuit.mint" to "intuit-inc/mint",
        "com.wf.wellsfargomobile" to "wells-fargo/wells-fargo",
        "com.chase.sig.android" to "jpmorgan-chase-co/chase",
        "com.citi.citimobile" to "citi/citi",
        "com.americanexpress.android.acctsvcs.us" to "american-express/american-express",
        "com.usaa.mobile.android.usaa" to "usaa/usaa",
        "com.ally.MobileBank" to "ally-bank/ally-bank",
        "com.capitalone.mobile" to "capital-one/capital-one",
        "com.discover.mobile" to "discover-financial-services/discover",
        "com.moneylion.android" to "moneylion/moneylion",
        "com.sofi.mobile" to "sofi/sofi",
        "com.chime.themis" to "chime/chime",
        "com.zellepay.zelle" to "early-warning-services-llc/zelle",
        "com.transferwise.android" to "wise/wise",
        "com.remitly.remitly" to "remitly/remitly",
        "com.moneygram.mobile" to "moneygram-international/moneygram",

        // =====================================================================
        // TRAVEL & TRANSPORTATION
        // =====================================================================
        "com.google.android.apps.maps" to "google-inc/google-maps",
        "com.waze" to "waze/waze",
        "com.ubercab" to "uber/uber",
        "com.lyft.android" to "lyft-inc/lyft",
        "com.booking" to "booking-com/booking-com",
        "com.airbnb.android" to "airbnb-inc/airbnb",
        "com.expedia.bookings" to "expedia-inc/expedia",
        "com.tripadvisor.tripadvisor" to "tripadvisor/tripadvisor",
        "com.skyscanner.android.main" to "skyscanner/skyscanner",
        "com.kayak.android" to "kayak/kayak",
        "com.trivago" to "trivago/trivago",
        "com.hotels.android" to "hotels-com/hotels-com",
        "com.grab.passenger" to "grabtaxi/grab",
        "bolt.driver" to "bolt-technology-ou/bolt",
        "com.flightradar24free" to "flightradar24/flightradar24",
        "com.google.android.apps.travel.onthego" to "google-inc/google-travel",
        "com.hostelworld.app" to "hostelworld/hostelworld",
        "com.vrbo.android" to "vrbo/vrbo",
        "com.agoda.mobile.consumer" to "agoda/agoda",
        "com.priceline.android.negotiator" to "priceline/priceline",
        "com.hopper.mountainview.play" to "hopper/hopper",
        "com.aa.android" to "american-airlines-inc/american-airlines",
        "com.united.mobile.android" to "united/united",
        "com.southwest.android" to "southwest/southwest",
        "com.ryanair.ryanair" to "ryanair/ryanair",
        "uk.co.easyjet.mapp" to "easyjet/easyjet",
        "com.lufthansa.android" to "lufthansa/lufthansa",
        "com.emirates.ek.android" to "emirates/emirates",
        "com.qatarairways.qmobapp" to "qatar-airways/qatar-airways",
        "com.turkishairlines.mobile" to "turkish-airlines/turkish-airlines",
        "citymapper.citymapper" to "citymapper/citymapper",
        "com.here.app.maps" to "here-global-b-v/here-wego",
        "com.mapswithme.maps.pro" to "mapsme/maps-me",
        "com.tomtom.gplay.navapp" to "tomtom-international-bv/tomtom-navigation",
        "com.inrix.android.ui" to "inrix/inrix",
        "com.gasbuddy.android" to "gasbuddy/gasbuddy",
        "me.lyft.driver" to "lyft-inc/lyft-driver",
        "com.ubercab.driver" to "uber-technologies-inc/uber-driver",

        // =====================================================================
        // NEWS & MEDIA
        // =====================================================================
        "com.google.android.apps.magazines" to "google-inc/google-news",
        "flipboard.app" to "flipboard/flipboard",
        "com.nytimes.android" to "the-new-york-times-company/ny-times",
        "com.cnn.mobile.android.phone" to "cnn/cnn",
        "com.bbc.news" to "bbc/bbc-news",
        "com.guardian" to "guardian-news-media/the-guardian",
        "com.foxnews.android" to "fox-news/fox-news",
        "com.washingtonpost.android" to "washington-post/washington-post",
        "com.reuters.news" to "reuters/reuters",
        "com.medium.reader" to "medium-corporation/medium",
        "com.espn.score_center" to "espn-2/espn",
        "com.bleacherreport.android.teamstream" to "bleacher-report/bleacher-report",
        "com.theScore" to "thescore/thescore",
        "com.yahoo.mobile.client.android.yahoo" to "yahoo/yahoo",
        "com.msn.news" to "microsoft-corporation/microsoft-news",
        "com.news.bing" to "microsoft-corporation/bing-news",
        "com.buzzfeed.android" to "buzzfeed/buzzfeed",
        "com.vice.android" to "vice-media/vice",
        "com.huffingtonpost.android" to "huffpost/huffpost",
        "au.com.newscorp.newsnetwork" to "news-corp/news-corp",
        "com.usatoday.android.news" to "usa-today/usa-today",
        "com.sfgate.sfnews" to "sfgate/sfgate",
        "com.politico.android" to "politico/politico",
        "com.substack.android" to "substack-inc/substack",
        "com.instapaper.android" to "instant-paper/instapaper",
        "com.ideashower.readitlater.pro" to "readitlater-inc/pocket",
        "com.feedly.android.core" to "devhd/feedly",
        "com.inoreader.android" to "inoreader/inoreader",
        "com.newsblur.android" to "newsblur/newsblur",
        "com.hola.launcher" to "hola/hola",
        "com.smartnews.android" to "smartnews-inc/smartnews",
        "com.topbuzz.videoen" to "topbuzz/topbuzz",
        "com.news.break.usa" to "particle-media/news-break",
        "com.opera.news" to "opera/opera-news",
        "com.squidapp.squid" to "squidapp/squid",
        "com.google.android.apps.books" to "google-inc/google-play-books",

        // =====================================================================
        // PHOTO & VIDEO EDITING
        // =====================================================================
        "com.vsco.cam" to "vsco/vsco",
        "com.picsart.studio" to "picsart/picsart-photo-studio",
        "com.niksoftware.snapseed" to "google-inc/snapseed",
        "com.adobe.lrmobile" to "adobe/lightroom",
        "com.adobe.psmobile" to "adobe/photoshop-express",
        "com.canva.editor" to "canva/canva",
        "com.camerasideas.instashot" to "camerasideas-corp/inshot",
        "com.kinemaster.editor.pro" to "kinemaster-corporation/kinemaster",
        "com.capcut.app" to "bytedance-pte-ltd/capcut",
        "com.lightricks.videoleap" to "lightricks-ltd/videoleap",
        "com.lightricks.facetune.free" to "lightricks-ltd/facetune",
        "com.pixlr.express" to "inmagine-lab/pixlr",
        "com.google.android.apps.photos" to "google-inc/google-photos",
        "com.instagram.layout" to "facebook-2/layout",
        "com.google.android.apps.youtube.creator" to "google-inc/youtube-studio",
        "video.like" to "bigo-technology-pte-ltd/likee",
        "com.photoroom.studio" to "photoroom/photoroom",
        "com.magisto" to "magisto/magisto",
        "com.vivavideo.videoeditor" to "quvideo/vivavideo",
        "com.vee.quik" to "gopro-inc/quik",
        "com.gopro.smarty" to "gopro-inc/gopro",
        "com.polarr.photoeditor" to "polarr/polarr",
        "com.beautycam.app" to "meitu-inc/beautycam",
        "com.meitu.beautycamera" to "meitu-inc/meitupic",
        "com.lomotif.android" to "lomotif-pte-ltd/lomotif",
        "com.vita.video.editor" to "snow-corp/vita",
        "com.snow.android" to "line-corp/snow",
        "com.cyberlink.powerdirector.DRA140120_05" to "cyberlink/powerdirector",
        "com.adobe.premiererush.samsungcampaign" to "adobe/premiere-rush",
        "com.splice.splice" to "splice/splice",

        // =====================================================================
        // GOOGLE APPS
        // =====================================================================
        "com.google.android.youtube" to "google-inc/youtube",
        "com.google.android.gm" to "google-inc/gmail",
        "com.google.android.apps.docs" to "google-inc/google-docs",
        "com.google.android.apps.docs.editors.sheets" to "google-inc/google-sheets",
        "com.google.android.apps.docs.editors.slides" to "google-inc/google-slides",
        "com.google.android.apps.meetings" to "google-inc/google-meet",
        "com.google.android.calendar" to "google-inc/google-calendar",
        "com.google.android.keep" to "google-inc/google-keep",
        "com.google.android.apps.drive" to "google-inc/google-drive",
        "com.google.android.apps.translate" to "google-inc/google-translate",
        "com.google.android.apps.messaging" to "google-inc/messages",
        "com.google.android.googlequicksearchbox" to "google-inc/google",
        "com.android.chrome" to "google-inc/chrome",
        "com.google.android.apps.tachyon" to "google-inc/google-duo",
        "com.google.android.inputmethod.latin" to "google-inc/gboard",
        "com.google.android.apps.fitness" to "google-inc/google-fit",
        "com.google.android.apps.classroom" to "google-inc/google-classroom",
        "com.grasshopper" to "google-inc/grasshopper",

        // =====================================================================
        // MICROSOFT APPS
        // =====================================================================
        "com.microsoft.teams" to "microsoft-corporation/microsoft-teams",
        "com.microsoft.office.outlook" to "microsoft-corporation/outlook",
        "com.microsoft.office.word" to "microsoft-corporation/microsoft-word",
        "com.microsoft.office.excel" to "microsoft-corporation/microsoft-excel",
        "com.microsoft.office.powerpoint" to "microsoft-corporation/powerpoint",
        "com.microsoft.skydrive" to "microsoft-corporation/onedrive",
        "com.microsoft.onenote" to "microsoft-corporation/onenote",
        "com.touchtype.swiftkey" to "microsoft-corporation/swiftkey",
        "com.microsoft.math" to "microsoft-corporation/microsoft-math",

        // =====================================================================
        // GAMES - ACTION & SHOOTER
        // =====================================================================
        "com.activision.callofduty.shooter" to "activision/call-of-duty-mobile",
        "com.activision.callofduty.warzone" to "activision/warzone-mobile",
        "com.tencent.ig" to "tencent/pubg-mobile",
        "com.pubg.newstate" to "pubg-corporation/pubg-new-state",
        "com.tencent.tmgp.pubgmhd" to "tencent-games/pubg-mobile-hd",
        "com.garena.game.ffsea" to "garena-international-ii/free-fire",
        "com.dts.freefireth" to "garena-international-ii/free-fire-max",
        "com.epicgames.fortnite" to "epic-games/fortnite",
        "com.supercell.brawlstars" to "supercell/brawl-stars",
        "com.riotgames.league.wildrift" to "riot-games/wild-rift",
        "com.criticalforceentertainment.criticalops" to "critical-force-entertainment/critical-ops",
        "com.gameloft.android.ANMP.GloftMCHM" to "gameloft/modern-combat-5",
        "com.madfingergames.deadtrigger2" to "madfinger-games/dead-trigger-2",
        "com.madfingergames.shadowgunlegends" to "madfinger-games/shadowgun-legends",
        "com.wb.goog.mkx" to "warner-bros-international-enterprises/mortal-kombat-x",
        "com.wb.goog.injustice.brawler2017" to "warner-bros-international-enterprises/injustice-2",
        "com.nekki.shadowfight3" to "nekki/shadow-fight-3",
        "com.nekki.shadowfight" to "nekki/shadow-fight-2",
        "com.pixonic.wwr" to "pixonic/war-robots",
        "com.axlebolt.standoff2" to "axlebolt/standoff-2",
        "com.rockstargames.gtasa" to "rockstar-games/gta-san-andreas",
        "com.rockstargames.gtavc" to "rockstar-games/gta-vice-city",

        // =====================================================================
        // GAMES - STRATEGY & RPG
        // =====================================================================
        "com.supercell.clashofclans" to "supercell/clash-of-clans",
        "com.supercell.clashroyale" to "supercell/clash-royale",
        "com.supercell.hayday" to "supercell/hay-day",
        "com.supercell.boom" to "supercell/boom-beach",
        "com.blizzard.wtcg.hearthstone" to "blizzard-entertainment/hearthstone",
        "com.riotgames.legendsofruneterra" to "riot-games/legends-of-runeterra",
        "com.plarium.raidlegends" to "plarium-global/raid-shadow-legends",
        "com.lilithgames.roc.gp" to "lilithgames/rise-of-kingdoms",
        "com.lilithgame.hgame.gp" to "lilithgames/afk-arena",
        "com.kabam.marvelbattle" to "kabam/marvel-contest",
        "com.scopely.marvel" to "scopely/marvel-strike-force",
        "com.netease.onmyoji.gl" to "netease/onmyoji",
        "com.miHoYo.GenshinImpact" to "mihoyo/genshin-impact",
        "com.HoYoverse.hkrpgoversea" to "hoyoverse/honkai-star-rail",
        "com.miHoYo.bh3global" to "mihoyo/honkai-impact-3rd",
        "com.ea.game.pvzfree_row" to "ea/plants-vs-zombies",
        "com.ea.game.pvz2_row" to "electronic-arts/pvz-2",
        "com.igg.castleclash_de" to "igg/castle-clash",
        "com.igg.android.mobileroyale" to "igg/mobile-royale",
        "com.innogames.foe" to "innogames/forge-of-empires",
        "com.funplus.stateofsurvival.gp" to "funplus/state-of-survival",
        "com.topwar.gp" to "topwar-studio/top-war",
        "com.yotta.lords" to "igg/lords-mobile",
        "com.nintendo.zara" to "nintendo/fire-emblem-heroes",
        "com.square_enix.android_googleplay.ffbraveexvius" to "square-enix/ffbe",
        "com.aniplex.fategrandorder.en" to "aniplex-inc/fate-grand-order",
        "com.netmarble.sknightsgb" to "netmarble/seven-knights",
        "com.tencent.arena.gp" to "tencent/arena-of-valor",
        "com.my.world.of.tanks.blitz" to "wargaming-group/world-of-tanks-blitz",
        "net.wargaming.wot.blitz" to "wargaming-group/wot-blitz",
        "com.wargaming.wows.blitz" to "wargaming-group/world-of-warships",

        // =====================================================================
        // GAMES - CASUAL & PUZZLE
        // =====================================================================
        "com.kiloo.subwaysurf" to "kiloo/subway-surfers",
        "com.king.candycrushsaga" to "king/candy-crush-saga",
        "com.king.candycrushsodasaga" to "king/candy-crush-soda",
        "com.king.candycrushjellysaga" to "king/candy-crush-jelly",
        "com.imangi.templerun2" to "imangi/temple-run-2",
        "com.innersloth.spacemafia" to "innersloth/among-us",
        "com.mojang.minecraftpe" to "mojang/minecraft",
        "com.roblox.client" to "roblox-corporation/roblox",
        "com.playrix.gardenscapes" to "playrix/gardenscapes",
        "com.playrix.homescapes" to "playrix/homescapes",
        "com.playrix.township" to "playrix/township",
        "com.playrix.fishdomdd.gplay" to "playrix/fishdom",
        "com.outfit7.talkingtom2" to "outfit7/talking-tom-2",
        "com.halfbrick.fruitninjax" to "halfbrick-studios/fruit-ninja",
        "com.rovio.angrybirds2.revo" to "rovio-entertainment-corporation/angry-birds-2",
        "com.rovio.dream" to "rovio/angry-birds-dream",
        "com.miniclip.eightballpool" to "miniclip/8-ball-pool",
        "com.fingersoft.hillclimb" to "fingersoft/hill-climb-racing",
        "com.fingersoft.hcr2" to "fingersoft/hill-climb-racing-2",
        "com.zynga.words3" to "zynga/words-with-friends",
        "com.etermax.preguntados.lite" to "etermax/trivia-crack",
        "com.bitstrip.bitstrips" to "bitstrips/bitmoji",
        "com.ketchapp.helix" to "ketchapp/helix-jump",
        "io.voodoo.paper2" to "voodoo/paper-io-2",
        "io.voodoo.crowdcity" to "voodoo/crowd-city",
        "com.azurgames.stackball" to "azurgames/stack-ball",
        "com.matchingham.games.royal.match" to "matchingham-games/royal-match",
        "com.gram.games.mergemagicr" to "gram-games/merge-magic",
        "com.gramgames.mergedragons" to "gram-games/merge-dragons",
        "com.peoplefun.wordcross" to "peoplefun/word-cross",
        "com.bitmango.go.wordcookies" to "bitmango/word-cookies",
        "com.wordscapes.levels" to "peoplefun/wordscapes",
        "com.peoplefun.wordle" to "peoplefun/wordle",
        "games.easybrain.crossword" to "easybrain/crossword",
        "com.zeptolab.ctr2.f2p.google" to "zeptolab/cut-the-rope-2",
        "com.ubisoft.hungrysharkworld" to "ubisoft-entertainment/hungry-shark-world",
        "com.ubisoft.hungrysharkevolution" to "ubisoft-entertainment/hungry-shark-evolution",
        "com.noodlecake.altosadventure" to "noodlecake-studios-inc/altos-adventure",
        "com.noodlecake.altosodyssey" to "noodlecake-studios-inc/altos-odyssey",
        "com.farseer.golf" to "playdemic/golf-clash",
        "com.playgendary.kickthebuddy" to "playgendary/kick-the-buddy",
        "com.matchington.mansion" to "firecraft-studios/matchington-mansion",

        // =====================================================================
        // GAMES - RACING & SPORTS
        // =====================================================================
        "com.ea.gp.fifamobile" to "electronic-arts/ea-fc-mobile",
        "com.firsttouchgames.dls7" to "first-touch-games/dream-league-soccer",
        "com.konami.pesam" to "konami/efootball",
        "com.ea.games.r3_row" to "electronic-arts/real-racing-3",
        "com.gameloft.android.ANMP.GloftA9HM" to "gameloft/asphalt-9",
        "com.gameloft.android.ANMP.GloftA8HM" to "gameloft/asphalt-8",
        "com.naturalmotiongames.csr2" to "naturalmotiongames/csr-racing-2",
        "com.sega.sonic" to "sega/sonic-dash",
        "com.miniclip.golf.battle" to "miniclip/golf-battle",
        "com.ea.games.nfs14_row" to "electronic-arts/need-for-speed",
        "com.ea.game.nfs.mobile" to "electronic-arts/nfs-no-limits",
        "com.carxtech.carxdrift2" to "carx-technologies/carx-drift-racing-2",
        "com.csr.csrracing2" to "naturalmotiongames-ltd/csr-2",
        "com.nba2k.android" to "2k/nba-2k-mobile",
        "com.ea.gp.nbamobile" to "ea/nba-mobile",
        "com.miniclip.footballstrike" to "miniclip/football-strike",
        "com.miniclip.basketballstars" to "miniclip/basketball-stars",
        "com.tennis.clash" to "wildlife-studios/tennis-clash",
        "com.zynga.mlb" to "zynga/mlb-tap-sports",
        "com.miniclip.pool" to "miniclip/pool",

        // =====================================================================
        // HEALTH & FITNESS
        // =====================================================================
        "com.strava" to "strava/strava",
        "com.myfitnesspal.android" to "myfitnesspal-inc/myfitnesspal",
        "com.calm.android" to "calm-com/calm",
        "com.headspace.android" to "headspace-inc/headspace",
        "com.nike.plusgps" to "nike-inc/nike-run-club",
        "com.nike.ntc" to "nike-inc/nike-training",
        "com.fitbit.FitbitMobile" to "fitbit-inc/fitbit",
        "com.samsung.android.health" to "samsung-electronics-co-ltd/samsung-health",
        "com.noom.coach" to "noom-inc/noom",
        "com.flo.health" to "flo-health/flo",
        "com.sweatco.sweatcoin" to "sweatco-ltd/sweatcoin",
        "com.runtastic.android" to "adidas/adidas-running",
        "com.mapmyrun.android2" to "under-armour/mapmyrun",
        "com.endomondo.android" to "under-armour/endomondo",
        "com.fitnesskeeper.runkeeper.pro" to "runkeeper/runkeeper",
        "com.freeletics.lite" to "freeletics-gmbh/freeletics",
        "com.sworkit.partner.workouts" to "sworkit/sworkit",
        "com.clue.android" to "biowink-gmbh/clue",
        "com.babycenter.pregnancytracker" to "babycenter/babycenter",
        "co.thefabulous.app" to "the-fabulous/fabulous",
        "com.habitnow.app" to "habitnow/habitnow",
        "com.yazio.android" to "yazio/yazio",
        "com.lifesum.android.lifesum" to "lifesum/lifesum",
        "com.loseit.android" to "lose-it/lose-it",
        "com.cronometer.android" to "cronometer/cronometer",
        "com.app.yoga.daily" to "daily-yoga/daily-yoga",
        "com.dowdog.yoga" to "down-dog-llc/down-dog",

        // =====================================================================
        // EDUCATION & LEARNING
        // =====================================================================
        "com.duolingo" to "duolingo/duolingo",
        "com.coursera.app" to "coursera/coursera",
        "com.udemy.android" to "udemy-inc/udemy",
        "com.linkedin.android.learning" to "linkedin/linkedin-learning",
        "com.quizlet.quizletandroid" to "quizlet/quizlet",
        "org.khanacademy.android" to "khan-academy/khan-academy",
        "com.sololearn" to "sololearn/sololearn",
        "co.babbel.mobile.android.en" to "babbel/babbel",
        "com.busuu.android.enc" to "busuu/busuu",
        "com.skillshare.Skillshare" to "skillshare/skillshare",
        "com.memrise.android.memrisecompanion" to "memrise/memrise",
        "com.photomath.app" to "photomath/photomath",
        "com.brainly" to "brainly/brainly",
        "com.chegg.study" to "chegg-inc/chegg-study",
        "com.grammarly.android.keyboard" to "grammarly/grammarly-kb",
        "com.grammarly" to "grammarly/grammarly",
        "com.cambly.mobile" to "cambly-inc/cambly",
        "com.italki.app" to "italki/italki",
        "com.rosettastone.mobile.learner" to "rosetta-stone/rosetta-stone",
        "com.drops.android" to "drops/drops",
        "com.hellotalk.android" to "hellotalk/hellotalk",
        "com.lingoda.app" to "lingoda-gmbh/lingoda",
        "com.mimo.application" to "mimo/mimo",
        "com.programming.hub.python" to "programming-hub/programming-hub",
        "com.freecodecamp.android" to "freecodecamp/freecodecamp",
        "com.datacamp.android" to "datacamp/datacamp",
        "org.edx.mobile" to "edx/edx",
        "com.udacity.android" to "udacity/udacity",
        "com.codecademy.codecademy" to "codecademy/codecademy",
        "com.brilliant.android" to "brilliant-com/brilliant",
        "com.symbolab.android" to "symbolab/symbolab",
        "com.wolfram.android.alpha" to "wolfram/wolfram-alpha",
        "com.mathway" to "mathway/mathway",

        // =====================================================================
        // PRODUCTIVITY & UTILITIES
        // =====================================================================
        "com.lastpass.lpandroid" to "lastpass/lastpass",
        "com.onepassword.android" to "1password/1password",
        "com.bitwarden.ui" to "bitwarden/bitwarden",
        "org.torproject.torbrowser" to "tor-project/tor-browser",
        "com.todoist" to "doist/todoist",
        "com.ticktick.task" to "ticktick/ticktick",
        "com.anydo" to "anydo/any-do",
        "com.evernote" to "evernote/evernote",
        "com.automattic.simplenote" to "automattic/simplenote",
        "com.slack" to "slack-technologies-inc/slack",
        "us.zoom.videomeetings" to "zoom-inc/zoom",
        "com.trello" to "trello/trello",
        "com.asana.app" to "asana-inc/asana",
        "com.monday.android" to "monday-com/monday-com",
        "com.zapier.zaps" to "zapier/zapier",
        "com.ifttt.ifttt" to "ifttt/ifttt",
        "com.dropbox.android" to "dropbox-inc/dropbox",
        "com.box.android" to "box-inc/box",

        // =====================================================================
        // BROWSERS
        // =====================================================================
        "org.mozilla.firefox" to "mozilla/firefox",
        "com.opera.browser" to "opera/opera",
        "com.brave.browser" to "brave-software/brave-browser-fast-adblocker",
        "com.UCMobile.intl" to "ucweb-inc/uc-browser-safe-fast-video-downloader",
        "com.duckduckgo.mobile.android" to "duckduckgo/duckduckgo-privacy-browser",

        // =====================================================================
        // STREAMING & ENTERTAINMENT
        // =====================================================================
        "com.netflix.mediaclient" to "netflix-inc/netflix",
        "com.disney.disneyplus" to "disney/disney",
        "com.hbo.hbonow" to "hbo/max",
        "com.amazon.avod.thirdpartyclient" to "amazon/prime-video",
        "com.google.android.youtube.tv" to "google-inc/youtube-tv",
        "tv.pluto.android" to "pluto-inc/pluto-tv",
        "com.peacocktv.peacockandroid" to "peacock-tv/peacock",
        "com.paramount.paramount" to "paramount/paramount",
        "com.crunchyroll.crunchyroid" to "crunchyroll/crunchyroll",
        "com.funimation.funimation_play" to "funimation/funimation",
        "com.apple.atve" to "apple-inc/apple-tv",
        "com.curiositystream.tv" to "curiositystream/curiositystream",
        "com.hulu.plus" to "hulu/hulu",
        "com.sling" to "sling-tv/sling-tv",
        "com.fubotv.vtv" to "fubo-tv/fubotv",
        "com.philo.philo" to "philo/philo",
        "com.showtime.standalone" to "showtime-networks-inc/showtime",
        "com.starz.starzplay" to "starz/starz",
        "com.tubitv" to "tubi-tv/tubi",
        "com.plex.client.android" to "plex-inc/plex",
        "com.kodi.android" to "kodi/kodi",
        "com.vlc.android" to "videolabs/vlc",
        "com.mxtech.videoplayer.ad" to "mxtech/mx-player",
        "org.videolan.vlc" to "videolan/vlc",
        "com.dazn.android" to "dazn/dazn",
        "com.espn.espnandroid" to "espn/espn",
        "com.foxsports.android" to "fox-sports/fox-sports",
        "com.nbcsports.gold" to "nbcuniversal-media-llc/nbc-sports",
        "com.turner.tnt" to "turner/tnt",
        "com.discovery.discoverygo" to "discovery-communications-llc/discovery",
        "com.hallmark.hallmarkmovies" to "hallmark/hallmark",
        "com.cbs.app" to "cbs-interactive/cbs",
        "com.tbs.tbs" to "turner-broadcasting-system-inc/tbs"
    )

    /**
     * Gets the APKMirror URL for a given package name.
     * 
     * @param packageName The Android package name (e.g., "com.whatsapp")
     * @return Direct app page URL if in mapping, otherwise search URL
     */
    fun getUrl(packageName: String): String {
        val mapping = packageMappings[packageName]
        
        return if (mapping != null) {
            // Direct app page URL
            "https://www.apkmirror.com/apk/$mapping/"
        } else {
            // Fallback to search URL
            "https://www.apkmirror.com/?post_type=app_release&searchtype=app&s=$packageName"
        }
    }

    /**
     * Checks if the package has a direct mapping
     */
    fun hasDirectMapping(packageName: String): Boolean {
        return packageMappings.containsKey(packageName)
    }
}
